# Generated by Django 5.1.5 on 2025-05-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.FileField(default=1, upload_to='', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
